/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutomatoSwing;

import AutomatoAnalisadorLexico.AnalisadorLexico;
import AutomatoAnalisadorSintatico.AnalisadorSintatico;
import AutomatoException.GeneralException;
import java.util.Date;
import javax.swing.JScrollPane;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
//import java.awt

/**
 *
 * @author juanvmr
 */
public class AutomatoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AutomatoJFrame
     */
    public AutomatoJFrame() {
        initComponents();
        
        //scroll = new JScrollPane(EditorJTextField);
        EditorJTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                lastModified = null;
                lastModified = new Date();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                lastModified = null;
                lastModified = new Date();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                lastModified = null;
                lastModified = new Date();
            }
        });
        
        arquivo = new ArquivoJInternalFrame();
        arquivo.setVisible(false);
        
        confirmacao = new ConfirmacaoJInternalFrame();
        confirmacao.setVisible(false);
        
        PilhaLista = new Stack<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EditorJTextField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        PilhaJList = new javax.swing.JList<>();
        CompilarJButton = new javax.swing.JButton();
        JMenuBar = new javax.swing.JMenuBar();
        ArquivoJMenu = new javax.swing.JMenu();
        OpenFJMenuItem = new javax.swing.JMenuItem();
        SaveFJMenuItem = new javax.swing.JMenuItem();
        NewFJMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SairJMenuItem = new javax.swing.JMenuItem();
        AjudaMenu = new javax.swing.JMenu();
        SobreJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EditorJTextField.setColumns(20);
        EditorJTextField.setRows(5);
        jScrollPane1.setViewportView(EditorJTextField);

        jScrollPane2.setViewportView(PilhaJList);

        CompilarJButton.setText("Compilar");
        CompilarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompilarJButtonActionPerformed(evt);
            }
        });

        ArquivoJMenu.setText("Arquivo");

        OpenFJMenuItem.setText("Abrir arquivo");
        OpenFJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFJMenuItemActionPerformed(evt);
            }
        });
        ArquivoJMenu.add(OpenFJMenuItem);

        SaveFJMenuItem.setText("Salvar arquivo");
        SaveFJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFJMenuItemActionPerformed(evt);
            }
        });
        ArquivoJMenu.add(SaveFJMenuItem);

        NewFJMenuItem.setText("Novo arquivo");
        NewFJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFJMenuItemActionPerformed(evt);
            }
        });
        ArquivoJMenu.add(NewFJMenuItem);
        ArquivoJMenu.add(jSeparator1);

        SairJMenuItem.setText("Sair");
        SairJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairJMenuItemActionPerformed(evt);
            }
        });
        ArquivoJMenu.add(SairJMenuItem);

        JMenuBar.add(ArquivoJMenu);

        AjudaMenu.setText("Ajuda");

        SobreJMenuItem.setText("Sobre");
        SobreJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreJMenuItemActionPerformed(evt);
            }
        });
        AjudaMenu.add(SobreJMenuItem);

        JMenuBar.add(AjudaMenu);

        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompilarJButton)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CompilarJButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFJMenuItemActionPerformed
        //verificarSalvo();
        arquivo.setVisible(true);
        arquivo.setComponentsText("Digite a path do arquivo a ser aberto:", "Abrir", "Cancelar");
    }//GEN-LAST:event_OpenFJMenuItemActionPerformed

    private void NewFJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFJMenuItemActionPerformed
        //verificarSalvo();
        arquivo.setVisible(true);
        arquivo.setComponentsText("Digite a path do novo arquivo:", "Criar", "Cancelar");
    }//GEN-LAST:event_NewFJMenuItemActionPerformed

    private void SairJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairJMenuItemActionPerformed
        //verificarSalvo();
        System.exit(0);
    }//GEN-LAST:event_SairJMenuItemActionPerformed

    private void SobreJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreJMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Autor: Juan Victor May da Rosa");
    }//GEN-LAST:event_SobreJMenuItemActionPerformed

    private void SaveFJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFJMenuItemActionPerformed
        arquivo.setVisible(true);
        arquivo.setComponentsText("Digite a path do arquivo a ser salvo:", "Salvar", "Cancelar");
    }//GEN-LAST:event_SaveFJMenuItemActionPerformed

    private void CompilarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompilarJButtonActionPerformed
        AnalisadorLexico analisadorLexico = new AnalisadorLexico();
        //analisadorLexico.setPilhaLexica();
        try{
            PilhaToken = analisadorLexico.percorrerFita(EditorJTextField.getText());
        }
        catch(GeneralException e){
            e.printStackTrace();
        }
        
        PilhaToken.forEach((s) -> {
            PilhaLista.push(s.toString());
        });
        PilhaJList.setListData(PilhaLista);
        
        //AnalisadorSintatico analisadorSintatico = new AnalisadorSintatico(analisadorLexico.getPilhaLexica());
        
        //analisadorSintatico.analiseSintatica();
    }//GEN-LAST:event_CompilarJButtonActionPerformed

    private void verificarSalvo(){
        if(lastSave.before(lastModified)){
            this.setEnabled(false);
            confirmacao.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomatoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutomatoJFrame().setVisible(true);
            }
        });
    }

    private ArquivoJInternalFrame arquivo;
    private ConfirmacaoJInternalFrame confirmacao;
    private JScrollPane scroll;
    private Stack<Integer> PilhaToken;
    private Stack<String> PilhaLista;
    private Date lastSave;
    private Date lastModified;
    //private TextLineNumber
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AjudaMenu;
    private javax.swing.JMenu ArquivoJMenu;
    private javax.swing.JButton CompilarJButton;
    private javax.swing.JTextArea EditorJTextField;
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JMenuItem NewFJMenuItem;
    private javax.swing.JMenuItem OpenFJMenuItem;
    private javax.swing.JList<String> PilhaJList;
    private javax.swing.JMenuItem SairJMenuItem;
    private javax.swing.JMenuItem SaveFJMenuItem;
    private javax.swing.JMenuItem SobreJMenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
