/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutomatoSwing;

/**
 *
 * @author juanvmr
 */
public class ConfirmacaoJInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConfirmacaoJInternalFrame
     */
    public ConfirmacaoJInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalvarJButton = new javax.swing.JButton();
        ContinuarJButton = new javax.swing.JButton();
        ConfirmacaoJLabel = new javax.swing.JLabel();

        SalvarJButton.setText("Salvar");
        SalvarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarJButtonActionPerformed(evt);
            }
        });

        ContinuarJButton.setText("Continuar");
        ContinuarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarJButtonActionPerformed(evt);
            }
        });

        ConfirmacaoJLabel.setText("Deseja salvar antes de continuar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ContinuarJButton)
                .addGap(18, 18, 18)
                .addComponent(SalvarJButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfirmacaoJLabel)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfirmacaoJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarJButton)
                    .addComponent(ContinuarJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContinuarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarJButtonActionPerformed
        confirm = false;
    }//GEN-LAST:event_ContinuarJButtonActionPerformed

    private void SalvarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarJButtonActionPerformed
        confirm = true;
    }//GEN-LAST:event_SalvarJButtonActionPerformed

    public boolean getConfirm(){
        return confirm;
    }
    
    private boolean confirm;
    //private;
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmacaoJLabel;
    private javax.swing.JButton ContinuarJButton;
    private javax.swing.JButton SalvarJButton;
    // End of variables declaration//GEN-END:variables
}
